project_id = "dzcymhdhvkjqaxmvqvoz"

[auth]
enabled = true

[auth.sms]
enable_signup = true
enable_confirmations = true
template = "Your Banjara Bandhan OTP verification code is: {{ .Code }}"

[auth.sms.twilio]
enabled = true
account_sid = "isGXR3PVqDqTphWLp9YU4sLYChKiSKjog4Mv"
auth_token = "76be1e2db3d9d4a3428c0dacba81ebbb"
sender_number = "+15107377366"