project_id = "dzcymhdhvkjqaxmvqvoz"

[auth]
enabled = true

[auth.sms]
enable_signup = true
enable_confirmations = true
template = "Your Banjara Bandhan OTP verification code is: {{ .Code }}"

[auth.sms.twilio]
enabled = true
account_sid = "env(TWILIO_ACCOUNT_SID)"
auth_token = "env(TWILIO_AUTH_TOKEN)"
sender_number = "env(TWILIO_PHONE_NUMBER)"